service:
  name: ifttt-toggl

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs8.10

functions:
  toggl:
    handler: src/index.toggl
    events:
      - http:
          method: post
          path: /on
      - http:
          method: post
          path: /off
      - http:
          method: post
          path: /toggle
