service:
  name: toggl

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

functions:
  toggl:
    handler: handler.toggl
    events:
      - http:
          method: post
          path: /on
      - http:
          method: post
          path: /off
